### ISSUE TITLE
AVPlayer 线上示例报错

### ISSUE THREAD

**Issue by yzydeveloper** [zhaohappy/libmedia#1]
测试m3u8的源，控制台提示：
![image](https://github.com/zhaohappy/libmedia/assets/50061726/09248afe-9989-4716-b66a-7d5696162f88)

**Comment by zhaohappy** [comment]
m3u8 和 dash 的索引文件只能是网络的 url 地址，web 上是无法根据索引文件读取本地文件的。

**Comment by yzydeveloper** [comment]
> m3u8 和 dash 的索引文件只能是网络的 url 地址，web 上是无法根据索引文件读取本地文件的。

![image](https://github.com/zhaohappy/libmedia/assets/50061726/15ed69fd-e486-4a10-a25d-03684aceae62)
线上的地址也报错呀

**Comment by zhaohappy** [comment]
应该可以了，有多个分辨率的时候解析 m3u8 文件有点问题。

**Comment by yzydeveloper** [comment]
> 应该可以了，有多个分辨率的时候解析 m3u8 文件有点问题。

现在AVPlayer可以上生产吗？

**Comment by yzydeveloper** [comment]
![image](https://github.com/zhaohappy/libmedia/assets/50061726/e8bb931d-6372-4ccf-b529-ea9eff057904)

播放这个源会报错，https://vod.lyhuicheng.com/20240504/A6UA2jTC/index.m3u8

**Comment by zhaohappy** [comment]
> > 应该可以了，有多个分辨率的时候解析 m3u8 文件有点问题。
> 
> 现在AVPlayer可以上生产吗？

你需要什么功能呢，目前还没有用于生产，你需要的话可以试试，有问题我可以提供支持。另外目前 m3u8 还不支持加密的流，所以上面那个链接还播放不了。

**Comment by yzydeveloper** [comment]
> > > 应该可以了，有多个分辨率的时候解析 m3u8 文件有点问题。
> > 
> > 
> > 现在AVPlayer可以上生产吗？
> 
> 你需要什么功能呢，目前还没有用于生产，你需要的话可以试试，有问题我可以提供支持。另外目前 m3u8 还不支持加密的流，所以上面那个链接还播放不了。

好的好的，
还有个问题是，使用webcodecs解码也会用到wasm吗？

**Comment by zhaohappy** [comment]
> > > > 应该可以了，有多个分辨率的时候解析 m3u8 文件有点问题。
> > > 
> > > 
> > > 现在AVPlayer可以上生产吗？
> > 
> > 
> > 你需要什么功能呢，目前还没有用于生产，你需要的话可以试试，有问题我可以提供支持。另外目前 m3u8 还不支持加密的流，所以上面那个链接还播放不了。
> 
> 好的好的， 还有个问题是，使用webcodecs解码也会用到wasm吗？

目前 AVPlayer 的策略是视频用 webcodecs 作为硬解码器，wasm 作为软解码器，初始化解码器的时候会把硬解码器和软解码器都初始化，然后优先使用硬解码器，硬解码器解码失败之后会回退到软解码器。音频只使用 wasm 解码器，没有使用 webcodecs。如果你需要调整策略的话，需要手动改代码了。

**Comment by yzydeveloper** [comment]
> > > > > 应该可以了，有多个分辨率的时候解析 m3u8 文件有点问题。
> > > > 
> > > > 
> > > > 现在AVPlayer可以上生产吗？
> > > 
> > > 
> > > 你需要什么功能呢，目前还没有用于生产，你需要的话可以试试，有问题我可以提供支持。另外目前 m3u8 还不支持加密的流，所以上面那个链接还播放不了。
> > 
> > 
> > 好的好的， 还有个问题是，使用webcodecs解码也会用到wasm吗？
> 
> 目前 AVPlayer 的策略是视频用 webcodecs 作为硬解码器，wasm 作为软解码器，初始化解码器的时候会把硬解码器和软解码器都初始化，然后优先使用硬解码器，硬解码器解码失败之后会回退到软解码器。音频只使用 wasm 解码器，没有使用 webcodecs。如果你需要调整策略的话，需要手动改代码了。

![image](https://github.com/zhaohappy/libmedia/assets/50061726/e634bd84-d31d-4225-923d-4c6bf5329e17)

在windows环境构建会报错...输出的代码好像也不太对

**Comment by zhaohappy** [comment]
那个 wat2wasm 是 unix 可执行程序，你有 WSL 环境吗，有的话在里面编译。我后面提交一个 windows 的执行文件。

**Comment by yzydeveloper** [comment]
没wsl环境，老哥你有时间改改吧，我本地也装一下wsl

**Comment by zhaohappy** [comment]
> 没wsl环境，老哥你有时间改改吧，我本地也装一下wsl
 
 windows 可以编译了，删掉之前的重新 clone 试试。

**Comment by yzydeveloper** [comment]
> > 没wsl环境，老哥你有时间改改吧，我本地也装一下wsl
> 
> windows 可以编译了，删掉之前的重新 clone 试试。

可以编译啦，辛苦辛苦

**Comment by zhaohappy** [comment]
> https://github.com/Momo707577045/m3u8-downloader/blob/master/aes-decryptor.js https://github.com/video-dev/hls.js/blob/master/src/crypt/decrypter.ts
> 
> 有关m3u8解密的代码，应该能有所帮助吧

可以，我后面看看加一下这个。

**Comment by yzydeveloper** [comment]
老哥，可以加个联系方式吗？有啥问题向您反馈的及时点

**Comment by zhaohappy** [comment]
> 老哥，可以加个联系方式吗？有啥问题向您反馈的及时点

微信号： zhaohappy_
