### ISSUE TITLE
Make libraries `common` and `cheap` be part of this repository.

### ISSUE THREAD

**Issue by Mng12345** [zhaohappy/libmedia#16]
As the title.

**Comment by zhaohappy** [comment]
we use git submodule to depend on ```cheap```  and ```common```. Do you think there are any problems in this way? You can add parameters ```--recursive``` to git clone command to clone this repository with ```cheap```  and ```common```.

**Comment by Mng12345** [comment]
Thanks, i download the source files by choosing zip file not using git clone, the `cheap` and `common` directories are empty.
