### ISSUE TITLE
peakU() mothod not found

### ISSUE THREAD

**Issue by ikigai-kevin-k** [zhaohappy/libmedia#18]
Thanks again for your provided [example for adding packet event ](https://github.com/zhaohappy/libmedia/discussions/17)🙏🙇

When I added the logic above and re-compile, I found that:

1. There lacked some ts files in the src/common/math/ (e.g. align.ts, median.ts, crc8.ts) which only exist in the later-version in your [common](https://github.com/zhaohappy/common) repo, so I copied them into src/common/math/ and re-compiled, then the file-not-found errors solved.
2. In the [/src/avformat/codecs/ac3.ts, line 211](https://github.com/zhaohappy/libmedia/blob/773fbfd4eedefc39fac5124abbbbf91b8b5d9653/src/avformat/codecs/ac3.ts#L211): 
```typescript
info.bitstreamId = bitReader.peekU() & 0x1f
```
the `peekU()` method was not found, after I replaced with `peekU1()`, which is defined in the BitReader class, the method-not-found error solved. I am not a very experienced open-source collaborator, hence not sure this trivial issue is whether worthful to create a individual PR to fix it so I decided to post it as an issue first.

**Comment by zhaohappy** [comment]
It looks like you didn't sync the submodule of common when you pull libmedia. Yon can use ```git pull --recurse-submodules``` to sync libmedia with all submodules or execute ```git submodule update --recursive``` after use ```git pull``` to sync libmedia. You can check out the git commands of submodule for details.
