### ISSUE TITLE
关于播放器鲁棒性问题

### ISSUE THREAD

**Issue by lixiang4u** [zhaohappy/libmedia#22]
播放器在播放一些特殊场景的资源时，会遇到播放失败等问题

1、播放文件不支持HEAD请求时，会导致播放失败

HEAD失败请求，有一个http status 206请求，后续无资源请求发起
![1729753972432](https://github.com/user-attachments/assets/8e45a504-ad9d-479b-a5c7-358ba61ba060)

![image](https://github.com/user-attachments/assets/aa1447f0-df21-4dca-8db2-14bfbbd69a41)

![image](https://github.com/user-attachments/assets/519e6d65-cce5-47c4-879c-b39fa70a77f8)

使用video标签元素可以正常播放
_貌似是直接GET请求资源，然后cancel，再次发起 content-range 请求？_
![image](https://github.com/user-attachments/assets/920936b5-7f15-4935-be27-423297b70f06)

![image](https://github.com/user-attachments/assets/f6a4d594-50c5-4cc5-a845-9119a51c9904)

[相关mp4文件地址（该地址可能因时间等问题而无法访问）](https://media-tjwq-fy-home.tj3oss.ctyunxs.cn/FAMILYCLOUD/4839bf22-70c1-4d66-b6ba-58010898decd.mp4?x-amz-CLIENTTYPEIN=PC&AWSAccessKeyId=0Lg7dAq3ZfHvePP8DKEU&x-amz-limitrate=61440&response-content-type=video/mp4&x-amz-UID=300000534202485&response-content-disposition=attachment%3Bfilename%3D%22%E5%BC%82%E5%BD%A2%E5%A4%BA%E5%91%BD%E8%88%B02024.mp4%22%3Bfilename*%3DUTF-8%27%27%25E5%25BC%2582%25E5%25BD%25A2%25E5%25A4%25BA%25E5%2591%25BD%25E8%2588%25B02024.mp4&x-amz-OPERID=300000534202632&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=FAMILY&Signature=EhN9jUkXb1cjMjWpXJlAneFsoNI%3D&Expires=1729761530&x-amz-FSIZE=3767239833&x-amz-UFID=324251161015832564)

2、m3u8文件在服务端被设置为 Content-Disposition 头时无法正常播放

使用video标签元素可以正常播放

m3u8资源是否可以直接判断内容为 ```#EXTM3U``` 开头即可？

**Comment by zhaohappy** [comment]
例子2有测试链接吗，我这没有复现

**Comment by lixiang4u** [comment]
> 例子2有测试链接吗，我这没有复现

测试资源文件：https://guandanwang.oss-cn-shanghai.aliyuncs.com/debug/files/efa9eda176bcaa9a1bde4ba15ba2fd7c.m3u8

说明：
1、原生video标签无法播放
2、使用 [dplayer](https://dplayer.diygod.dev/) 播放器可以播放
测试代码如下
```code
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- no-referrer 可以有效防止加载资源文件时出现对端服务器检测来源而不返数据问题 -->
    <meta name="referrer" content="no-referrer">
    <title>dplayer播放测试</title>
    <style type="text/css">
        #dplayer {
            width: 500px;
            height: 280px;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/dplayer@1.27.1/dist/DPlayer.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@1.5.17/dist/hls.min.js"></script>

</head>
<body>

<div id="dplayer"></div>

<script>
  window.onload = function () {
    const dp = new DPlayer({
      container: document.getElementById('dplayer'),
      video: {
        quality: [
          {
            url: 'https://guandanwang.oss-cn-shanghai.aliyuncs.com/debug/files/efa9eda176bcaa9a1bde4ba15ba2fd7c.m3u8',
            type: 'hls',
          },
        ],
        defaultQuality: 0,
      },
    });
    dp.play()
  }

</script>

</body>
</html>
```

**Comment by lixiang4u** [comment]
> 例子2有测试链接吗，我这没有复现

上述问题可能描述可能有误，并不一定是Content-Disposition导致的问题

测试资源链接：[地址](http://106.15.56.178:38386/api/m3u8p?q=https://guandanwang.oss-cn-shanghai.aliyuncs.com/debug/files/efa9eda176bcaa9a1bde4ba15ba2fd7c.m3u8)


说明：
1、使用原生video标签也无法播放
2、使用dplayer可以播放，代码如下

```code
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- no-referrer 可以有效防止加载资源文件时出现对端服务器检测来源而不返数据问题 -->
    <meta name="referrer" content="no-referrer">
    <title>dplayer播放测试</title>
    <style type="text/css">
        #dplayer {
            width: 500px;
            height: 280px;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/dplayer@1.27.1/dist/DPlayer.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@1.5.17/dist/hls.min.js"></script>

</head>
<body>

<div id="dplayer"></div>

<script>
  window.onload = function () {
    const dp = new DPlayer({
      container: document.getElementById('dplayer'),
      video: {
        quality: [
          {
            url: 'http://106.15.56.178:38386/api/m3u8p?q=https://guandanwang.oss-cn-shanghai.aliyuncs.com/debug/files/efa9eda176bcaa9a1bde4ba15ba2fd7c.m3u8',
            type: 'hls',
          },
        ],
        defaultQuality: 0,
      },
    });
    dp.play()
  }

</script>

</body>
</html>
```

**Comment by zhaohappy** [comment]
你这个链接不带文件后缀，没有当成 m3u8 走了普通的 fetch ioloader 所以报了格式不支持。

**Comment by lixiang4u** [comment]
还能支持吗，还是就这样没问题的？
因为实际过程中有些m3u8文件是做了中转或者代理什么的

**Comment by zhaohappy** [comment]
我在 load 方法的第二个参数添加了 options 参数，你外面传一下 ext: 'm3u8'  就可以了。HEAD 不支持的也好了。

**Comment by lixiang4u** [comment]
感谢

**Comment by zhaohappy** [comment]
我再想想吧，目前的架构这个会把流程打乱了导致代码逻辑出现混乱。

**Comment by zhaohappy** [comment]
在试一下

**Comment by lixiang4u** [comment]
> 在试一下

有文件没提交吗，编译报错

```code
      TS2305: Module '"common/types/type"' has no exported member 'HttpOptions'.
      TS2339: Property 'ioReader' does not exist on type 'RtspSession'.
      TS2305: Module '"common/types/type"' has no exported member 'Range'.
      TS2307: Cannot find module 'common/network/textMessage/message' or its corresponding type declarations.
      TS2339: Property 'NETWORK_ERROR' does not exist on type 'typeof IOError'.
```

**Comment by zhaohappy** [comment]
执行这个更新子模块 ```git submodule update --recursive```

**Comment by lixiang4u** [comment]
可以了
