### ISSUE TITLE
示例中看不到 使用WebCodecs api 硬解hevc 的例子 感觉设置了硬解 也不起作用。都是wasm软解

### ISSUE THREAD

**Issue by gihtubnmjf** [zhaohappy/libmedia#24]
示例中看不到 使用WebCodecs api 硬解hevc 的例子 感觉设置了硬解 也不起作用。都是wasm软解。请问怎么才能看到WebCodecs 硬解的例子

**Comment by zhaohappy** [comment]
你是指播放器 demo 还是直接用 api 写代码

**Comment by zhaohappy** [comment]
播放器优先使用硬解，不用设置。api 看这个[decode](https://github.com/zhaohappy/libmedia/blob/master/examples/decode.ts)。把 WasmVideoDecoder 换成WebVideoDecoder 传 enableHardwareAcceleration: true 。hevc 硬解需要硬解支持。

**Comment by gihtubnmjf** [comment]
你好 还是有点看不懂。WebCodecs api 硬解hevc  可以写个demo页面吗？

**Comment by zhaohappy** [comment]
[hardwareDecode](https://github.com/zhaohappy/libmedia/blob/master/examples/hardwareDecode.ts) 你把它编出来写一个 html 输入一个 hevc 的 flv 文件就解码出来了。

**Comment by gihtubnmjf** [comment]
https://ks3-cn-beijing.ksyun.com/ksplayer/h265/outside_demo/v1.1.3/720P2M30fpsh265-wasmtest.flv  解码失败

[src\avcodec\webcodec\VideoDecoder.ts][line 223] [error] decode error, InvalidStateError: Failed to execute 'decode' on 'VideoDecoder': Cannot call 'decode' on a closed codec.
1 decode error

**Comment by zhaohappy** [comment]
你这个码流应该有问题，硬解会失败，只能回退到软解。我转封装成 mp4 用 video 元素播放 chrome 也无法播放。

**Comment by zhaohappy** [comment]
之前改动一个地方出现 bug 了，已经修复

**Comment by gihtubnmjf** [comment]
onReceiveFrame(frame) {
      // 这里拿到解码出的帧
      console.log('receive frame', frame.timestamp)
      frame.close()
    },
    这个函数 我收到了回调  但是 用canvas截图 什么图像都没有显示出来。不知道什么原因？能写个例子示范一下吗？
    

![BF7CB3BC-0CA2-404a-8294-0D59B36D5E2D](https://github.com/user-attachments/assets/39e64418-7717-4e4c-bb9d-7bc94c0faf83)

**Comment by zhaohappy** [comment]
可以看看这个 [videoRender](https://github.com/zhaohappy/libmedia/blob/master/examples/videoRender.ts)
