### ISSUE TITLE
关于60帧raw视频流卡顿和播放延迟问题

### ISSUE THREAD

**Issue by 1415798891** [zhaohappy/libmedia#26]
播放延迟问题：播放30帧的视频流没有出现卡顿问题，但是有1秒左右的延迟，通过设置
`new window.AVPlayer({
    ......
    jitterBufferMax: 0.02,
    jitterBufferMin: 0.01,
    preLoadTime:1,
    lowLatency: true,
})`这几个参数并没有变化，这个延迟是无法修改的吗？

60帧视频流卡顿问题：播放60帧的raw h265视频流卡顿很严重，是从websocket获取的视频流，下面这是根据src/avnetwork/ioLoader/WebSocketIOLoader.ts写的一个自定义loader，经过打印，差不多16-20毫秒会触发一次read方法，这个自定义loader应该是没问题的；但是播放器初始化的日志打印是30fps，请问是有其他的参数设置吗？还是内部的帧率计算有问题？
`[src/avplayer/AVPlayer.ts][line 1355] [info] 
AVPlayer version v0.1.1-4-g36d81ec Copyright (c) 2024-present the libmedia developers
Input #0, raw_h265, from '[object WebSocket]':
  Duration: 00:00:00.000, start: 00:00:00.000, bitrate: 251660 kbps/s
  Stream #0:0 Video: hevc (Main), yuv420p(tv, bt709), 720x480 [SAR: 1:1 DAR 3:2], 251660 kbps/s, 30.00 fps, 30.00 tbr, 1000k tbn
    Metadata:
      naluLengthSizeMinusOne: 3`

`class MyIOLoader extends window.AVPlayer.IOLoader.CustomIOLoader {
  ws: WebSocket;
  url: string
  status: number
  protected readQueue: Uint8Array[] = [];
  protected consume: ((value: void | PromiseLike<void>) => void) | null
  constructor(url: string) {
    super()
    this.url = url;
    this.status = 0;
    this.consume = null
  }

  get ext() {
    return 'h265'
  }

  get name() {
    return this.ws
  }

  get minBuffer(): number {
    return 0
  }

  async open() {
    return new Promise((resolve) => {
      this.ws = new WebSocket(this.url);
      this.ws.binaryType = 'arraybuffer';
      const openMessage = JSON.stringify({
        t: 'open',
        c: 'ch1',
        v: 'NA',
      })

      this.ws.onopen = (ev: Event) => {
        this.ws?.send(openMessage);
        console.log("Socket connect success.");
        this.status = IOLoaderStatus.BUFFERING
        resolve(0)
      }
      this.ws.onerror = (ev: Event) => {
        this.status = IOLoaderStatus.ERROR
        resolve(IOError.NETWORK_ERROR)
        if (this.consume) {
          this.consume()
        }
      }
      this.ws.onclose = (ev: Event) => {
        console.log("Socket closed.");
      }
      this.ws.onmessage = (e) => {
        if (typeof e.data == 'string') {
          return;
        }
        this.readQueue.push(new Uint8Array(e.data))
        if (this.consume) {
          this.consume()
        }
      }
    })
  }

  private async readInterval(buffer: Uint8ArrayInterface, preLen: int32 = 0): Promise<number> {
    let pos = 0

    while (this.readQueue.length && pos < buffer.length) {
      const cache = this.readQueue.shift()
      // console.log(this.readQueue,cache);
      if (cache.length > buffer.length - pos) {
        buffer.set(cache.subarray(0, buffer.length - pos), pos)
        this.readQueue.unshift(cache.subarray(buffer.length - pos))
        pos = buffer.length
      }
      else {
        buffer.set(cache, pos)
        pos += cache.length
      }
    }

    if (pos > 0 || preLen) {
      return pos + preLen
    }

    if (this.status === IOLoaderStatus.COMPLETE || this.status === IOLoaderStatus.IDLE) {
      return pos > 0 ? (pos + preLen) : (preLen > 0 ? preLen : IOError.END)
    }

    if (this.status === IOLoaderStatus.ERROR) {
      return pos > 0 ? (pos + preLen) : (preLen > 0 ? preLen : IOError.NETWORK_ERROR)
    }

    await new Promise<void>((resolve) => {
      this.consume = resolve
    })

    this.consume = null
    // console.log(buffer, preLen);

    return this.readInterval(buffer, preLen)
  }

  // inter = Date.now()
  async read(buffer, options) {
    // write data to buffer
    const len = await this.readInterval(buffer)
    // console.log(Date.now() - this.inter)
    // this.inter= Date.now()
    return len
  }

  async seek(pos, options) {
    // seek if can
  }

  async size() {
    // return total size if has
  }

  async stop() {
    // stop ioloader
    if (this.ws) {
      this.ws.close()
      this.ws = null
    }
    this.status = IOLoaderStatus.COMPLETE
    if (this.consume) {
      this.consume()
    }
  }
}`

**Comment by zhaohappy** [comment]
裸流需要自己传播放帧率，现在默认是 30 帧；延时 1 秒还不够吗，设置太低了容易卡；设置成直播模式。

**Comment by 1415798891** [comment]
看了最新的commit，已经知道怎么修改了，感谢大佬回复。
最低延时可以根据需要自己调整当然是最好的了

**Comment by zhaohappy** [comment]
live 模式可以设置。
