### ISSUE TITLE
播放器在播放“不连帧”的情况下加载过小导致卡顿

### ISSUE THREAD

**Issue by xuanhen2013** [zhaohappy/libmedia#28]
<img width="1914" alt="image" src="https://github.com/user-attachments/assets/e11f5920-7d24-467a-968f-a2519766cad3">

播放视频帧不连续片段会导致疯狂加载卡顿, 使用的视频地址: https://www.123865.com/s/lnRVjv-1tpw3

**Comment by zhaohappy** [comment]
你这个 mp4 先存一大段视频数据之后再存一大段音频数据会导致来回 seek。这种视频并不适合 url 播放。目前默认不触发 seek 的最大音视频帧间隔为 1 秒。

**Comment by zhaohappy** [comment]
不好控制，需要缓存的大小是不可控的，最极端的情况是文件前半部分全是视频帧，后半部分全是音频帧，几乎要把文件全缓存下来才能播放，seek 也不好做。 建议用 ffmpeg 重新封装一下。这种视频不常见，封装得不专业。
