### ISSUE TITLE
我有一个 websocket 直播流，怎么在官方的 demo 中进行播放呢？

### ISSUE THREAD

**Issue by Greasen** [zhaohappy/libmedia#32]
我有一个 websocket 直播流，怎么在官方的 demo 中进行播放呢？
https://zhaohappy.github.io/libmedia/test/avplayer.html
流地址：ws://172.26.6.185/liv/3.live.flv

**Comment by zhaohappy** [comment]
没有开放直接播 ws 的 url，可以写一个 CustomIOLoader。

**Comment by zhaohappy** [comment]
现在可以了，放开了

**Comment by Greasen** [comment]
非常感谢，我重新拉一下代码在试试

**Comment by Greasen** [comment]
> 非常感谢，我重新拉一下代码在试试

根据文档上的操作，拉下来了代码后，安装成功，运行 npm run build-avplayer-dev 报错：
![image](https://github.com/user-attachments/assets/c852522b-ae95-4396-b8a2-1c2ad44207f1)

**Comment by zhaohappy** [comment]
![Uploading image.png…]()
你在这个地方打印一下这个错误看报的什么错

**Comment by Greasen** [comment]
> ![image](https://private-user-images.githubusercontent.com/19706653/397900537-74566c10-6c00-434a-802d-9abe14050c70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NDk5NjIsIm5iZiI6MTczNDc0OTY2MiwicGF0aCI6Ii8xOTcwNjY1My8zOTc5MDA1MzctNzQ1NjZjMTAtNmMwMC00MzRhLTgwMmQtOWFiZTE0MDUwYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAyNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMjk5MzA2ZmJlNDU5ZWVmMDMyZDE5NTZjYzNiMDRkNmQxYzUwNWJkYzNmNzBkNTI0MjFhOGVkMzU3ZDE1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.76D6nj7hE8nrNce-FlqHfSoX_xNQZtY3R24k-_XE8MU)
> 
> 你在这个地方打印一下这个错误看报的什么错

![image](https://github.com/user-attachments/assets/f8ad4cec-0c02-42ff-bbec-7573b7146e64)

**Comment by Greasen** [comment]
我们之前一直用的是 mse 的硬件解码，但是在生产运行的时候发现，很多客户的机器不具备硬件条件，导致hevc无法解码，所以打算采用 wasm 的方案尝试一下，我看了一些库，libmedia 这个库取了webcodec和wasm的长处，是非常不错的，我们是拿来做实时监控的，不知道这个库是否适合在生产中运行。

**Comment by zhaohappy** [comment]
看着像是缺少一些 wat2wasm.exe 依赖的动态库。

**Comment by zhaohappy** [comment]
> 我们之前一直用的是 mse 的硬件解码，但是在生产运行的时候发现，很多客户的机器不具备硬件条件，导致hevc无法解码，所以打算采用 wasm 的方案尝试一下，我看了一些库，libmedia 这个库取了webcodec和wasm的长处，是非常不错的，我们是拿来做实时监控的，不知道这个库是否适合在生产中运行。

可以的

**Comment by Greasen** [comment]
> 看着像是缺少一些 wat2wasm.exe 依赖的动态库。

大佬看看，缺什么动态库。我这是按照官网一步步操作的，是不是有什么遗漏？

**Comment by zhaohappy** [comment]
按理说应该不存在啥特殊的动态库，都是系统里面有的，我也没遇见过这种情况。你用 cmd 编译看看，把那行命令单独拿出来执行看看。

**Comment by Greasen** [comment]
> 按理说应该不存在啥特殊的动态库，都是系统里面有的，我也没遇见过这种情况。你用 cmd 编译看看，把那行命令单独拿出来执行看看。

cmd 编译没有出错。
![image](https://github.com/user-attachments/assets/6ba83858-ea8f-4fef-84df-b3e9b1aaf31e)
谢谢大佬

**Comment by Greasen** [comment]
有一个问题，这个 wasm 的调用cpu软解，cpu 的占用率非常高有没有优化的空间啊？
![image](https://github.com/user-attachments/assets/ae385612-623f-4608-8a8f-d55df29a6667)
![image](https://github.com/user-attachments/assets/2bd77f6d-5edb-4713-8e7e-17613be957c1)
![image](https://github.com/user-attachments/assets/916faf2c-7e01-4614-8be9-42021b2fb929)

**Comment by zhaohappy** [comment]
1. 关掉浏览器控制台，这个对 wasm 的速度影响很大；
2. 使用 simd 解码器；

**Comment by Greasen** [comment]
好的大佬。有一个问题，我这边控制设备，画面的延迟有点高，大概有2-3s的样子，是不是我有的配置没有勾上，还是 wasm 的软解延迟就是比较高的？
![image](https://github.com/user-attachments/assets/a155e24e-a7fa-4d16-96ab-ab05e6469389)

**Comment by zhaohappy** [comment]
可以慢慢追上来的，大概追到 1 秒的延时。

**Comment by Greasen** [comment]
> 可以慢慢追上来的，大概追到 1 秒的延时。

大佬，我这边长时间测试了一下，分别放了 ffplay、mpegts.js、 libmedia 的 demo，ffplay 延迟大概在毫秒级别，mpegts.js 大概在1s内，libmedia 大概有4s-7s。

**Comment by Greasen** [comment]
> > 可以慢慢追上来的，大概追到 1 秒的延时。
> 
> 大佬，我这边长时间测试了一下，分别放了 ffplay、mpegts.js、 libmedia 的 demo，ffplay 延迟大概在毫秒级别，mpegts.js 大概在1s内，libmedia 大概有4s-7s。

只是在 wasm 软解的情况下。

**Comment by zhaohappy** [comment]
你的 cpu 是啥型号

**Comment by Greasen** [comment]
> 你的 cpu 是啥型号, ffplay 是没法播放 ws 的流的， mpegts.js 是没法软解 265 的，你是怎么个对比法。

是不同的流，mpegts.js 用的是 硬解，libmedia 的 demo 用的 wasm 的软解
