### ISSUE TITLE
厉害了，可惜看不懂，要是文档再丰富些就好了，先starred了

### ISSUE THREAD

**Issue by johnbaoss** [zhaohappy/libmedia#6]
找了很久，这应该是目前最好的解决方案了，能取wasm和WebCodecs的两家之长，真正实现在web端剪辑，而不依靠服务端，减少服务端的资源消耗，绝对有前景，加油！～

**Comment by zhaohappy** [comment]
需要有音视频基础才能看得明白，可以慢慢学。文档后面会慢慢完善。我一个人精力也比较有限，有更多的人加入一起开发维护就更好了。

**Comment by imzlh** [comment]
我都是看源码写interface的，感谢TypeScript
为了打包进Vite，我写了一个JavaScript负责中间层，类型都需要重新写，那很悲催

**Comment by zhaohappy** [comment]
现在文档已经有了
